# Introduction to `numpy`
`numpy` (short for numeric python) allows for a diverse range of scientific computations. For us, however, it will be a tool to compute matrix multiplications.

### Installation
You can install `numpy` using the following commands:


using `pip`: `pip install numpy`\
using `Anaconda`: `conda install numpy`

### Feeding a matrix to `numpy`
The following code shows how to store the matrix
$$A:=\begin{bmatrix}1&3\\4&5\end{bmatrix}$$
in `numpy`: as a list of lists which correspond to the row vectors of $A$.

In [1]:
# Import the package
import numpy as np

A = np.matrix([
    [1,3],
    [4,5]
])

A

matrix([[1, 3],
        [4, 5]])

### Matrix multiplication
Consider $B:=\begin{bmatrix}1&5&4\\6&9&0\end{bmatrix}$. Then $A\cdot B$ is computed in `numpy` via the `matmul` function:

In [2]:
B = np.matrix([
    [1,5,4],
    [6,9,0]
])

np.matmul(A,B)

matrix([[19, 32,  4],
        [34, 65, 16]])

### Matrix transposes
To calculate $A^T$, use the `np.transpose` function:

In [3]:
np.transpose(A)

matrix([[1, 4],
        [3, 5]])

### Working with matrix inverses
The inverse $A^{-1}$ of $A$ can be calculated using `linalg.inv`:

**Note**: Using the inverse explicitly can lead to numerical instabilities. We will try to avoid it if possible and use "work-araounds".<br>
**Example**: To get the solution for a system of form $A=xB$, we don't compute $x$ by $x = A^{-1}B$ but instead use the numpy function `linalg.solve`.

In [4]:
A_inv = np.linalg.inv(A)

print(A_inv)
print()
print(np.matmul(A_inv, B))
print()
print(np.linalg.solve(A,B))

[[-0.71428571  0.42857143]
 [ 0.57142857 -0.14285714]]

[[ 1.85714286  0.28571429 -2.85714286]
 [-0.28571429  1.57142857  2.28571429]]

[[ 1.85714286  0.28571429 -2.85714286]
 [-0.28571429  1.57142857  2.28571429]]


Here we don't see a difference, as $A$ isn't ill-condidioned. With other $A$s it would change.<br>
You can try to find an A where using the direct inverse gives you a different solution to x as using `linalg.solve`. 

### Row/column manipulation using `numpy`

To access the $i$-th row we use the following command:
`A[i,:]`
(keep in mind, we start counting from 0).

Similarly to access the $i$-th colum we use:
`A[:,i]`.

In [5]:
#First row of A
print(A[0,:])
print()

#Second column of A
print(A[:,1])

[[1 3]]

[[3]
 [5]]


### Number of rows and columns in a matrix

To get the number of **rows** in a matrix use: `A.shape[0]`.<br>
To get the number of **columns** in a matrix use: `A.shape[1]`.<br>
$B$ is used as an example, as $A$ is a square matrix and it doesn't make it clear that those are seperate outputs.

In [6]:
#Rows
print("Rows: " + str(B.shape[0]))
print("Columns: " + str(B.shape[1]))

Rows: 2
Columns: 3


### Accessing elements of the matrix

To get the element $a_{i,j}$ we use:
`A[i,j]`.

In [7]:
#Element in first row, second column
a_01 = A[0,1]
print(a_01)

3
