# The Simplex Method

**Goal**: Solve an LP using the 2-phase simplex algorithm.


In [1]:
# You're given the pivot function from last weeks programming assignment
import numpy as np

def pivot(T,i,k):
    T_pivot = np.copy(T)
    T_pivot[i,:] = T[i,:] / T[i,k] #Step (i)
    for l in range(0,T.shape[1]): #Step (ii)
        for j in range(0,T.shape[0]):
            if(j!=i):
                T_pivot[j,l] = T[j,l] - T[j,k] * T[i,l] / T[i,k]
    return T_pivot


In [2]:
# Write down the tableau of the auxiliary LP

T = np.array([
    [0, 0, 0, 0, 0, 0, 0, 1, 0],
    [1, 0, 0, 0, 0, 1, 3,-1,15],
    [0, 1, 0, 0, 0, 3,-1,-1,-6],
    [0, 0, 1, 0, 0, 1, 0,-1, 4],
    [0, 0, 0, 1, 0, 2, 1,-1,10],
    [0, 0, 0, 0, 1,-1,-1,-1,-3]
], dtype=float)


In [3]:
# Perform an exchange step on the tableau, such that the resulting tableau is feasible

T = pivot(T,2,7) # exchange x_0 and y_2, i. e. pivot on position (3,8)
print(T)

[[ 0.  1.  0.  0.  0.  3. -1.  0. -6.]
 [ 1. -1.  0.  0.  0. -2.  4.  0. 21.]
 [-0. -1. -0. -0. -0. -3.  1.  1.  6.]
 [ 0. -1.  1.  0.  0. -2.  1.  0. 10.]
 [ 0. -1.  0.  1.  0. -1.  2.  0. 16.]
 [ 0. -1.  0.  0.  1. -4.  0.  0.  3.]]


In [4]:
T = np.array([
    [0, 0, 0, 0, -3, -1, 0],
    [1, 0, 0, 0, -1, -1, -1],
    [0, 1, 0, 0, 2, -1, 4],
    [0, 0, 1, 0, 1, 2, 7],
    [0, 0, 0, 1, -1, 1, 2]
], dtype=float)

In [5]:
T = pivot(T,1,4)
print(T)

[[-3.  0.  0.  0.  0.  2.  3.]
 [-1. -0. -0. -0.  1.  1.  1.]
 [ 2.  1.  0.  0.  0. -3.  2.]
 [ 1.  0.  1.  0.  0.  1.  6.]
 [-1.  0.  0.  1.  0.  2.  3.]]


In [6]:
T = pivot(T,2,0)
print(T)

[[ 0.   1.5  0.   0.   0.  -2.5  6. ]
 [ 0.   0.5  0.   0.   1.  -0.5  2. ]
 [ 1.   0.5  0.   0.   0.  -1.5  1. ]
 [ 0.  -0.5  1.   0.   0.   2.5  5. ]
 [ 0.   0.5  0.   1.   0.   0.5  4. ]]


In [7]:
T = pivot(T,3,5)
print(T)

[[ 0.   1.   1.   0.   0.   0.  11. ]
 [ 0.   0.4  0.2  0.   1.   0.   3. ]
 [ 1.   0.2  0.6  0.   0.   0.   4. ]
 [ 0.  -0.2  0.4  0.   0.   1.   2. ]
 [ 0.   0.6 -0.2  1.   0.   0.   3. ]]


In [8]:
T = pivot(T,1,5)
print(T)

[[ nan  nan  nan  nan  nan  nan  nan]
 [ nan  inf  inf  nan  inf  nan  inf]
 [ nan  nan  nan  nan  nan  nan  nan]
 [ nan -inf -inf  nan -inf  nan -inf]
 [ nan  nan  nan  nan  nan  nan  nan]]


D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: invalid value encountered in true_divide
  
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in double_scalars
  # Remove the CWD from sys.path while we load stuff.
D:\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: RuntimeWarning: divide by zero encountered in double_scalars
  # Remove the CWD from sys.path while we load stuff.


In [9]:
# Redo phase I, but this time already keep track of the original objective

T = np.array([
    [0, 0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0,-2,-1, 0, 0], # simply add the original objective row from the beginning
    [1, 0, 0, 0, 1, 3,-1,15],
    [0, 1, 0, 0, 1, 0,-1, 4],
    [0, 0, 1, 0, 2, 1,-1,10],
    [0, 0, 0, 1,-1,-1,-1,-3]
], dtype=float)
T = pivot(T,5,6)
T = pivot(T,5,5)
T = np.delete(T,6,1) # delete column corresponding to x0
T = np.delete(T,0,0) # delete auxiliary objective row
print(T)

[[ 0.  0.  0. -1. -1.  0.  3.]
 [ 1.  0.  0.  3. -2.  0.  6.]
 [ 0.  1.  0.  0.  1.  0.  4.]
 [ 0.  0.  1.  1.  1.  0.  7.]
 [-0. -0. -0. -1.  1.  1.  3.]]


In [17]:
T = np.array([
    [0, 0, 0, 3, -4, 0],
    [1, 0, 0, -2,-4, -6], # simply add the original objective row from the beginning
    [0, 1, 0, -1, 1, 1],
    [0, 0, 1, -1, 2, 8]
], dtype=float)

T = pivot(T,1,3)
print(T)

[[  1.5   0.    0.    0.  -10.   -9. ]
 [ -0.5  -0.   -0.    1.    2.    3. ]
 [ -0.5   1.    0.    0.    3.    4. ]
 [ -0.5   0.    1.    0.    4.   11. ]]


In [18]:
T = pivot(T,2,4)
print(T)

[[-0.16666667  3.33333333  0.          0.          0.          4.33333333]
 [-0.16666667 -0.66666667 -0.          1.          0.          0.33333333]
 [-0.16666667  0.33333333  0.          0.          1.          1.33333333]
 [ 0.16666667 -1.33333333  1.          0.          0.          5.66666667]]


In [19]:
T = pivot(T,3,0)
print(T)

[[ 0.  2.  1.  0.  0. 10.]
 [ 0. -2.  1.  1.  0.  6.]
 [ 0. -1.  1.  0.  1.  7.]
 [ 1. -8.  6.  0.  0. 34.]]


In [20]:
T = np.array([
    [1, 2, 0, 0, 0, 3],
    [6, 1, 1, 0,0, 7], # simply add the original objective row from the beginning
    [9, -4, 0, 0, 1, -1],
    [1, 3, 0, 1, 0, 2]
], dtype=float)

T = pivot(T,3,1)
print(T)

[[ 0.33333333  0.          0.         -0.66666667  0.          1.66666667]
 [ 5.66666667  0.          1.         -0.33333333  0.          6.33333333]
 [10.33333333  0.          0.          1.33333333  1.          1.66666667]
 [ 0.33333333  1.          0.          0.33333333  0.          0.66666667]]
