## A pivoting function
We now want to implement a function `pivot(T, i, j)` which takes in a short tableau $T$, and replaces the basis variable corresponding to row $i$ of the tableau by the variable corresponding to column $j$ of the tableau. By convention, the tableau $T$ should include the objective function row as the first row (the row with index $0$), and the right hand sides as the last column.

To avoid accidental selection of a pivot from the objective function row or the column of right-hand sides, your function should check that the input indices $i$ and $j$ are indeed pointing at a potential pivot. If not, the function should print a message saying so, and return the input tableau. Similarly, if the indicated pivot element is zero (in which case the pivoting step cannot be performed), the function should print a message saying so, and return the input tableau.
If a non-zero pivot is given, the pivoting step should be carried out, and the new tableau should be returned. Additionally, the function should print a message indicating whether or not the pivot was legal for phase II of the simplex method.

Complete the given framework below to obtain the pivoting function with the desired functionality.

In [1]:
def pivot(T,i,j):
    
    if (i == 0 or j == T.shape[1] - 1): # Check if the indices are not pointing at a potential pivot
        print("[Error] Given indices are not pointing at a potential pivot.")
        return T

    if (T[i, j] == 0): # Check if the indicated pivot is zero
        print("[Error] Given pivot is zero, step cannot be performed.")
        return T
    
    rat = []
    flag = 0
    for k in range(1, T.shape[0]):
        if T[k, j] > 0:
            rat.append(T[k, -1] / T[k, j])
    if rat is not None and T[i, -1] / T[i, j] == min(rat):
        flag = 1
    if (T[0, j] < 0 and flag == 1): # Check if indicated pivot is legal for phase II of Simplex Method
        print("[Info] Given pivot is legal.")
    else:
         print("[Warning] Given pivot is illegal.")
    
    # Implement pivoting step here
    T_pivoted = np.matrix(np.zeros_like(T))
    for m in range(T.shape[0]):
        for n in range(T.shape[1]):
            if m == i and n == j:
                T_pivoted[m, n] = 1 / T[i, j]
            elif m == i:
                T_pivoted[m, n] = T[m, n] / T[i, j]
            elif n == j:
                T_pivoted[m, n] = -T[m, n] / T[i, j]
            else:
                T_pivoted[m, n] = T[m, n] - T[m, j] * T[i, n] / T[i, j]

    return T_pivoted

## Testing your implementation
To check whether your implementation works, use your function to reproduce the following pivot steps from the lecture notes:

![](pivoting_fig2.png)

This can be done, for example, by running the code below:

In [6]:
import numpy as np
T = np.matrix([
    [-400,-900,0],
    [1,4,40],
    [2,1,42],
    [1.5,3,36]
])

T = pivot(T,2,0)
print(T)

[Info] Given pivot is legal.
[[ 2.00e+02 -7.00e+02  8.40e+03]
 [-5.00e-01  3.50e+00  1.90e+01]
 [ 5.00e-01  5.00e-01  2.10e+01]
 [-7.50e-01  2.25e+00  4.50e+00]]
